[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "api"
source = "sprint5-with-bugs/API"

[[services]]
name = "ui"  
source = "sprint5-with-bugs/UI"
